import type { Metadata } from "next";
import { Gochi_Hand, Inder } from "next/font/google";
import "./globals.css";
import { ClientLayout } from "./ClientLayout";

const inder = Inder({
  subsets: ["latin"],
  variable: "--font-inder",
  weight: "400",
});

const gochi = Gochi_Hand({
  subsets: ["latin"],
  variable: "--font-gochi",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" className={`${inder.variable} ${gochi.variable}`}>
      <body
        className={`font-sans antialiased`}
      >
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
